### ISSUE TITLE
Cordova-ios build issue

### ISSUE THREAD

**Issue by Mustafsak** [Appboy/appboy-cordova-sdk#18]
The SDK doesn't work with Cordova-ios and ionic 3.

## Steps to reproduce

```
$ ionic start le-ionic-appboy blank
$ cd le-ionic-appboy/
$ ionic cordova platform add ios
$ ionic cordova build ios
```

 ** **BUILD SUCCEEDED** **

```
$ ionic cordova plugin add https://github.com/appboy/appboy-cordova-sdk#master:/plugin/ --save
```
support for subdirectories is deprecated and will be removed in Cordova@7
fork the plugin and remove subdirectories
```
$ ionic cordova plugin add https://github.com/Loisirsencheres/appboy-cordova-sdk --save
$ ionic cordova build ios
```

** **BUILD FAILED** **

fatal error: ‘SDWebImage/UIImageView+WebCache.h’ file not found
#import <SDWebImage/UIImageView+WebCache.h>`

## Versions

```
node -v = v8.9.1
npm -v = 5.5.1
cordova -v = 7.1.0
cordova-ios = 4.5.3
```

**Comment by radixdev** [comment]
Hey @Mustafsak,

We've updated the Braze Cordova SDK to version 2.4.0, which fixes the subdirectory issue for Cordova 7. Thank you for bringing up the lack of compatibility.

On the other hand, Cordova 7 appears to have broken symlinks in `.framework` files such as SDWebImage. This is what caused `ionic cordova plugin add https://github.com/appboy/appboy-cordova-sdk#master:/plugin/ --save` to have the file not found error. To get around this, you'll have to:
1. Locally clone the Braze Cordova sdk `git clone https://github.com/Appboy/appboy-cordova-sdk.git` on your machine
2. Point cordova to that local sdk `ionic cordova plugin add PATH/TO/SDK`
3. The iOS build should succeed after these steps.

In the future, we're going to investigate workarounds to the Cordova-cli 7 symlink breakage issue since a manual integration is not preferred.

Please let me know if you have any future questions,
Julian

**Comment by Mustafsak** [comment]
hello @radixdev 

Thanks for the update, I have followed those steps but the build is still failed with the same error.
Do you have another solution?

**Comment by radixdev** [comment]
Hey @Mustafsak ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
