### ISSUE TITLE
requestImmediateDataFlush does not accept callback

### ISSUE THREAD

**Issue by drewrygh** [Appboy/appboy-cordova-sdk#59]
According to the docs, this call should take a callback that is invoked once the flush is successful: https://js.appboycdn.com/web-sdk/latest/doc/modules/appboy.html#requestimmediatedataflush

It doesn't appear that the cordova sdk supports passing a callback to this call: https://github.com/Appboy/appboy-cordova-sdk/blob/master/www/AppboyPlugin.js#L351

**Comment by Bucimis** [comment]
Hi @drewrygh, the Cordova SDK calls the native iOS/Android implementations of `requestImmediateDataFlush`, which both return `void`. As a result the Cordova js side also returns `void`. Do you have a particular use case for knowing whether the flush succeeded or not?

**Comment by drewrygh** [comment]
@Bucimis True — they both return void, but I am expecting the callback being passed to get called as soon as the data flush is completed. The docs suggest I should be able to do something like this:

```
function callback() {
  // Data flush has completed
}

requestImmediateDataFlush(callback);
```

This isn't currently possible since https://github.com/Appboy/appboy-cordova-sdk/blob/master/www/AppboyPlugin.js#L351 doesn't take any arguments.

**Comment by drewrygh** [comment]
The use case here is that when a user signs up for an account through our application, we register the user with Braze. We would like to pull the Braze content cards for this user as soon as the data flush is complete. Currently we don't have a way to determine when this happens, so we have an arbitrary timeout that waits a few seconds, and then tries to pull in the content cards. This is not an ideal solution, because Braze may not have completed the data flush and created the user if we don't wait long enough. When this happens, getContentCardsFromServer may not return anything because the user doesn't yet exist in Braze's system.

**Comment by Bucimis** [comment]
@drewrygh thanks for the context. Even with a callback this would still be an issue because Content Card writes happen asynchronously outside the request lifecycle, i.e. a data flush response doesn't guarantee Content Card availability for cards triggered based on data in that flush. We're aware of this issue and investigating solutions from the product side.

**Comment by drewrygh** [comment]
@Bucimis I see, that makes sense though. Thanks for the update.

**Comment by radixdev** [comment]
Hi @drewrygh ,

Adding callbacks to this method would have to first be accomplished in the native SDKs directly as a product request. Since the native methods do not currently accept callbacks, we cannot add them, at the moment, to the Cordova plugin.

To solve your immediate issue, I would recommend requesting a content card update with some backoff if no cards are returned immediately. I.e. do flush, request cards, if no cards are available, wait some period of time, then request again (with some maximum number of tries).
