### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jstoup111** [Appboy/appboy-cordova-sdk#9]
Does this include the SDK for iOS10 rich notifications?

**Comment by radixdev** [comment]
Hi @jstoup111 ,

To get your app working with rich notifications, please visit our [documentation](https://www.appboy.com/documentation/iOS10_Rich_Notifications). You'll also need to add some additional code to your app, for which we've provided [some sample code](https://github.com/Appboy/appboy-ios-sdk/blob/master/Example/StopwatchNotificationService/NotificationService.m). 

Please let me know if you have any further questions,
Julian

**Comment by jstoup111** [comment]
Hey Julian,

I've done this in my cordova app, and am using your REST API to send a notification with `asset_url` and `asset_file_type` in the `apple_push` payload. My asset_url does a redirect to the correct image, but I'm not seeing anything when I send the notification. Any thoughts on where I should look to see what's happening here?

I'm also not seeing the same dashboard as I see in the documentation. Hope I'm not missing something and you can point me in the right direction.

**Comment by radixdev** [comment]
Can you share the push payload that your NotificationService receives?

**Comment by jstoup111** [comment]
I'd be happy to. What is the best way for me to do that? Debugging and sending a push doesn't send me a push unless I'm using a Testflight build.

**Comment by jstoup111** [comment]
This is the payload I'm sending to your API.

```
 messages: { apple_push: { alert: 'whatsup', sound: 'yazda_alert.caf', asset_url: 'https://api.yazdaapp.com/clubs/1/banner', asset_file_type: 'png' }}
```

**Comment by radixdev** [comment]
Few things:
1. Can you try using a development certificate and sending a push to yourself in debug mode? You'll need to upload that development certificate to our dashboard to do this. I'd reccommend creating a test App Group that uses this development certificate as to not disrupt your production apps. You can still use our REST api to test sending messages.
2. Can you clarify "I'm not seeing anything when I send the notification."? Do you mean that a non-rich notification gets displayed or that no notification gets displayed at all? It could be that the image is too large and the download times out.
3. The rich notification screen in the dashboard can be reached via "Create Campaign" -> "Push Notification" -> "iOS Push".

**Comment by jstoup111** [comment]
Sure I'll try that. 

2. I'm not seeing an image. The alert still goes through, but there is no media associated with it.
3. I did that but am not seeing the fields for the rich notification. Are the pages cached?

**Comment by radixdev** [comment]
Hey @jstoup111 ,

After some debugging with your image url/payload, the issue is that your cdn is deemed an "insecure connection" and throws an error during the download. Using our sample notification service code, the error crops up [at this line](https://github.com/Appboy/appboy-ios-sdk/blob/master/Example/StopwatchNotificationService/NotificationService.m#L77).

> Printing description of error:
Error Domain=NSURLErrorDomain Code=-1022 "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection." UserInfo={NSUnderlyingError=0x1003313a0 {Error Domain=kCFErrorDomainCFNetwork Code=-1022 "(null)"}, NSErrorFailingURLStringKey=http://cdn.yazdaapp.com/uploads/club/banner/1/73017bcb-d8a3-495b-97a7-a77a0aff5b10.png, NSErrorFailingURLKey=http://cdn.yazdaapp.com/uploads/club/banner/1/73017bcb-d8a3-495b-97a7-a77a0aff5b10.png, NSLocalizedDescription=The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.}

The fix was relatively simple and was found [here](http://stackoverflow.com/questions/32631184/the-resource-could-not-be-loaded-because-the-app-transport-security-policy-requi). Essentially, you need to allow arbitrary loads in your info.plist to let the resource download finish.

Please let me know if this solves the issue on your side as well,
Julian

**Comment by jstoup111** [comment]
Thanks @radixdev I've tried hitting the HTTPS version and still not seeing any media `https://cdn.yazdaapp.com/uploads/club/banner/1/73017bcb-d8a3-495b-97a7-a77a0aff5b10.png` 

I'm seeing logging statements in the sample. Is there anyway for me to see the logging statements in my production build? I'm thinking that for whatever reason there is an error linking the Notification Service Extension to my app. Definitely don't think theres an issue with the payload that you're sending me.

Like I mentioned my dashboard doesn't allow me to send rich media. Is that potentially my issue as well? Maybe its not enabled for some reason or another?

**Comment by radixdev** [comment]
For my testing, I set my asset_url to `https://api.yazdaapp.com/clubs/1/banner` and `asset_file_type` to png, as with your original payload. I assume your cdn redirected that url to the one seen in the error message I posted. 
Xcode is a bit unintuitive for retrieving the logs from the Notification Extension. I instead opted to set a breakpoint where the error message gets logged. To do this, attach the Extension via debugger by the following steps in xcode: Product -> Attach to Process -> By Process Identifier (PID) or Name (name of your Extension).  As a simple test for whether the Extension is linked to your app, try setting the notification message to some test string. 

Once that's done, can you post in full the error message that gets generated?

Thanks,
Julian

**Comment by jstoup111** [comment]
Hey Julian, haven't gotten around to getting to this quite yet, but wanted to say thank you for all the help so far. I'll post an update when I have some more information. Really do appreciate the help.

**Comment by jstoup111** [comment]
I'm going to close this.

The issue was that for whatever reason, I didn't have the latest AppBoySDK. My git pull and removing/readding the plugin didn't work, so it didn't display the image. I have that working now. It's awesome and I'm super happy to have this functionality in my apps now :)
